### ISSUE TITLE
ERR saving metadata failed, this might be a bug

### ISSUE THREAD

**Issue by joelis10** [Arthi-chaud/Meelo#879]
**Describe the bug**
Sorry for opening another issue, but I can't for the life of me work out what's wrong with my setup. I've tried a bunch of different regex setups but I can't get the metadata to parse, it just keeps telling me ERR saving metadata failed, this might be a bug in the scanner container.

**To Reproduce**
1. Create a new library under Settings > Libraries, aimed at '/'
2. Click on Scan

**Expected behavior**
Meelo's scanner parses the metadata correctly and adds the songs to my library

**Version**
latest

**Additional context**

Example file path: `/1991/Odyssey (2022)/01 - On.m4a`

<details><summary>Scanner logs</summary>
note that this happens with any file type
<pre>
2:11PM INF Parsing successful file="02 - Police Heartbreaker.flac"

2:11PM ERR saving metadata failed, this might be a bug

2:11PM INF Parsing successful file="01 - Bad News.flac"

2:11PM ERR saving metadata failed, this might be a bug

2:11PM INF Parsing successful file="05 - Enter.flac"

2:11PM ERR saving metadata failed, this might be a bug

2:11PM INF Parsing successful file="07 - Out Of The Void.flac"

2:11PM ERR saving metadata failed, this might be a bug

2:11PM INF Parsing successful file="04 - Extreme Drift.flac"

2:11PM ERR saving metadata failed, this might be a bug
</pre>
</details> 

<details><summary>Settings.json</summary>
<pre>
{
	"trackRegex": [
		"^([\\/\\\\]+.*)*[\\/\\\\]+(?P<AlbumArtist>[^\\/\\\\]+)[\\/\\\\]+(?P<Album>.+?)\\s+\\((?P<Year>\\d{4})\\)[\\/\\\\]+(?P<Index>\\d+)\\s*-\\s*(?P<Track>[^\\/\\\\]+)\\..*$"
	],
	"metadata": {
		"source": "embedded",
		"order": "only",
		"useExternalProviderGenres": true
	},
	"providers": {
		"musicbrainz": {},
		"genius": {
			"apiKey": "xLBFdRGHdqLxyvj7NrwnRcUPOsm9gQmkps0hXHYfZNz4LkYWUrIpl4ISglhLdv1v"
		}
	},
	"compilations": {
		"useID3CompTag": true,
		"artists": [
			"Various Artists"
		]
	}
}
</pre>
</details> 

Is the issue my regex or track metadata? I ran all my songs through Lidarr first to format and tag them correctly but obviously I'm still having issues. Thanks again in advance!

**Comment by joelis10** [comment]
should be noted that I tried `path` and `preferred` for `path` and `order` respectively, but it still gave the same error.

**Comment by Arthi-chaud** [comment]
Hi @joelis10 , could you send the output of the `ffprobe [path to one of your files]` please?

**Comment by Arthi-chaud** [comment]
> should be noted that I tried `path` and `preferred` for `source` and `order` respectively, but it still gave the same error.

This is expected as you regex does not contain any named groups. Thus, only the embedded metadata is used

**Comment by joelis10** [comment]
```
  libavutil      58. 29.100 / 58. 29.100
  libavcodec     60. 31.102 / 60. 31.102
  libavformat    60. 16.100 / 60. 16.100
  libavdevice    60.  3.100 / 60.  3.100
  libavfilter     9. 12.100 /  9. 12.100
  libswscale      7.  5.100 /  7.  5.100
  libswresample   4. 12.100 /  4. 12.100
  libpostproc    57.  3.100 / 57.  3.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7a3749a41600] stream 0, timescale not set
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '01 - On.m4a':
  Metadata:
    major_brand     : M4A 
    minor_version   : 0
    compatible_brands: M4A mp42isom
    creation_time   : 2022-06-07T13:30:38.000000Z
    iTunSMPB        :  00000000 00000840 00000270 0000000000290550 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
    iTunNORM        :  00001436 0000153B 000068C5 0000A804 0000E57A 0000E54C 00007EAE 00007EAE 00004CBC 0000C817
    title           : On
    artist          : 1991
    album_artist    : 1991
    composer        : Frederick Russell Rossington Webb
    album           : Odyssey
    track           : 1/12
    disc            : 1/1
    compilation     : 0
    gapless_playback: 0
    date            : 2022-07-22
    account_id      : [my email here]
    copyright       : ℗ 2022 1991 / AEI
    rating          : 0
    media_type      : 1
    purchase_date   : 2024-10-05 18:22:21
    publisher       : I99I
    genre           : Drum And Bass; Electronic
    MusicBrainz Album Release Country: XW
    MusicBrainz Album Status: official
    MusicBrainz Album Type: album
    MusicBrainz Album Id: 57770ec0-7e13-4493-8976-6141aa3b65bc
    MusicBrainz Artist Id: c478aff3-2457-4cee-bdf1-6b85758f7cc6
    MusicBrainz Album Artist Id: c478aff3-2457-4cee-bdf1-6b85758f7cc6
    MusicBrainz Release Group Id: 293f5fad-928a-4cc0-a591-1457410d99f4
    MusicBrainz Track Id: d7c0c18f-a93d-4a16-a85f-fc8dd5e4db53
    Original Date   : 2022-07-22
    Original Year   : 2022
    MEDIA           : Digital Media
    MusicBrainz Release Track Id: 2f0f9562-92af-4674-a9ce-07948dec6321
  Duration: 00:01:01.02, start: 0.047889, bitrate: 364 kb/s
  Stream #0:0[0x1](eng): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 280 kb/s (default)
    Metadata:
      creation_time   : 2022-06-07T13:30:38.000000Z
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x0]: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 1200x1200 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)

```

**Comment by Arthi-chaud** [comment]
The metadata look complete.

I just published a release that fixes issues with metadata parsing. This might be related.

Could you please run `docker compose pull`, `docker compose stop` and `docker compose up -d`, and then try scanning again?

**Comment by joelis10** [comment]
As far as I can tell, it's still not fixed fully _but_ I do have a new error:
![Screenshot_20250208-150653.png](https://github.com/user-attachments/assets/6bac9d5b-c336-4ca2-8944-1fa00a3fda2f)

Apologies for the screenshot instead of text, I'm accessing my server remotely for now

**Comment by Arthi-chaud** [comment]
Oh I see what's wrong. The path of the library cannot be './' or '/'. You should tweak the 'DATA_DIR' variable in the .env and the library path so that the `library path != DATA DIR`

Let me know if you manage to make it work.
I only found out about this a couple of days ago, and have not fixed it yet

**Comment by joelis10** [comment]
I've changed my data directory from /mnt/media/Music to just /mnt/media and the directory inside Meelo to match, from / to /Music, but I'm still having issues. It's now saying this:
![Screenshot_20250208-154131.png](https://github.com/user-attachments/assets/cc74b5ea-a1e2-4a0b-b5c9-3fb0959900df)

I'll have a proper look when I'm home soon

**Comment by Arthi-chaud** [comment]
It should be "Music", not "/Music" (it should be a relative path)

**Comment by joelis10** [comment]
Soon after I sent my last comment, I realised that's probably what you meant and yep - it works now when using Music rather than /Music. Thanks again!

**Comment by Arthi-chaud** [comment]
Thanks for reporting this anyway, I'll open another issue about not being able to set the library path to `DATA_DIR`.
Thanks for your patience.
